### ISSUE TITLE
Matches should be stacked LIFO - last match on top and not at the bottom.

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#10]

**Comment by ililush** [comment]
![screenshot_9](https://cloud.githubusercontent.com/assets/18185033/21749700/a701ada8-d5ac-11e6-863f-c47b7c7e840e.png)

**Comment by ililush** [comment]
i think this should be re-opened.

**Comment by sebastientromp** [comment]
@ililush Have you been able to test this?

**Comment by ililush** [comment]
no, since i was not able to get new matches in the past few days, see other issues :)
