### ISSUE TITLE
On first image of the cards - the cards are beneath the frame of the board and not above

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#12]

**Comment by sebastientromp** [comment]
Not 100% sure what this is about yet, but could be linked to https://github.com/wwayne/react-tooltip/issues/241

**Comment by sebastientromp** [comment]
Also, waiting until integration as an iFrame to investigate this further

**Comment by ililush** [comment]
![screenshot_10](https://cloud.githubusercontent.com/assets/18185033/21749670/077a8d22-d5ac-11e6-9d78-7cc66603a93f.png)

**Comment by ililush** [comment]
fixed, can be closed.
