### ISSUE TITLE
If the window is full size the cards grow and are shown out of the frame (even though the board does not grow)

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#13]

**Comment by sebastientromp** [comment]
Not 100% sure what this is about, but could be linked to https://github.com/wwayne/react-tooltip/issues/241

**Comment by sebastientromp** [comment]
Also, waiting until integration as an iFrame to investigate this further

**Comment by ililush** [comment]
still happens, see attached 
![screenshot_11](https://cloud.githubusercontent.com/assets/18185033/21749496/0886d454-d5a8-11e6-9eec-7d9fa4af30a4.png)
mage

**Comment by ililush** [comment]
this is fixed - can be closed.
