### ISSUE TITLE
Location of cards is not constant (the cards jump)

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#16]
> just moving left and right over all cards at the user's hand

Might be caused by the different format of MSG cards, will have a look at it

**Comment by sebastientromp** [comment]
Would it be possible to have a reproduction scenario on that one? Ideally, a log file from the game that I can use to replay the same game

**Comment by ililush** [comment]
i cannot reproduce, so we can tag this solved for now.
