### ISSUE TITLE
Mouse over cards is not really precise

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#17]
scenario- you are mousing over all the cards in your hands. even though you have moved to the second card, you still see the first one. you need to be more than 1-2 milimeters on a card for it to show in mouse over.

**Comment by sebastientromp** [comment]
This is because the cards themselves are not straight rectangles. I'll see if I can use a clip path to trigger the mouse event only on the non-transparent part of the card

**Comment by sebastientromp** [comment]
@overwolf team: is this a blocking issue?

**Comment by ililush** [comment]
no, it's not blocking, but it's definitely something we will need to tackle.
![screenshot_13](https://cloud.githubusercontent.com/assets/18185033/21749530/b5d5eee2-d5a8-11e6-97d5-d3dedd361ce7.png)

**Comment by sebastientromp** [comment]
Got it. As said above I don't know yet how I'll tackle it, so not feeling confident to be able to solve it for this week

**Comment by ililush** [comment]
for me it's not critical for launch.

**Comment by ililush** [comment]
@sebastientromp can you please update where we are with this? did we trim any of the cards?

**Comment by sebastientromp** [comment]
Not yet - the last time we discussed with gai we left at the conclusion that there are no good way to resize animated gifs (which I use for golden images).
I have an action on my side to see if I can easily stop using animated gifs and replace them with only the first frame of the gif, and I could then use the same scaling technique on them.

**Comment by sebastientromp** [comment]
Recropping images doesn't work well after all. Spells and minions have a different outline - minions have stats spilling out from the card. This means that auto-cropping the cards will make spells bigger than minions (the card itself takes more of the space).

Any idea welcome, otherwise I guess the next step is to build a custom card renderer
