### ISSUE TITLE
Left click and drag over cards selects them all

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#18]

**Comment by ililush** [comment]
i understand that this needs some investigation, can we get a frame of time to understand what this will need to be solved? mainly, how long it will take? some time estimate :)

**Comment by ililush** [comment]
![screenshot_14](https://cloud.githubusercontent.com/assets/18185033/21749538/ff392acc-d5a8-11e6-97ce-52008183eae1.png)

**Comment by sebastientromp** [comment]
This is fixed on the source code, but maybe not in the distribution I send you. So you'll get it with the next version :)

**Comment by ililush** [comment]
does that means that this issue should be open?

**Comment by sebastientromp** [comment]
It's fixed in the source control, which is my reference for closed / open (this means that you could take the source, build it and get the fix). In other words, no further work is needed except build a new release. Can this definition work for you?

**Comment by ililush** [comment]
this can be closed.
