### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#2]
- [x] Remove bootstrap.css.map and bootstrap.min.css.map
- [x] Do you need the PNG images in this exact binary format?  Because using tinypng you can reduce all images dramatically
- [x] fonts - do you need all 4 font formats?
- [ ] background.min.js and shelf.min.js - when comparing their content - are almost identical. Can you, maybe, create a third js file that holds shared code?

**Comment by ililush** [comment]
hi, is there an action item for us here? do you need assistance with it?
