### ISSUE TITLE
win/lose indication in match carousel is wrong

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#20]
We won both games, and are shown to have lost it. Screenshot attached:
![screenshot_15](https://cloud.githubusercontent.com/assets/18185033/21749732/4d11384e-d5ad-11e6-9ff6-d11a5882b51c.png)

**Comment by sebastientromp** [comment]
Could you attach the game log file?

**Comment by sebastientromp** [comment]
I've been able to reproduce and it will be fixed with the next load

**Comment by ililush** [comment]
fixed, this can be closed
