### ISSUE TITLE
what is the rule for the fast forward button? is it based on time? Turn?

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#21]
trying to figure the logic. current use of the button is not very effective.

**Comment by sebastientromp** [comment]
Next turn. There should be a tooltip that says this though, will check why it doesn't show up

**Comment by sebastientromp** [comment]
Not fixed yet, for some reason the "title" attribute isn't shown when mousing over the controls (it is shown when integrated in the website though, so there might be something to make it work when integrated in an iFrame)

**Comment by ililush** [comment]
@sebastientromp maybe raise this issue in our channel to see if anyone has any idea how to solve it?

**Comment by ililush** [comment]
there are still two tooltips missing:
 - View opponent's card
 - switch places with opponent
![missing_tooltips](https://cloud.githubusercontent.com/assets/18185033/21973812/e60eb1ce-dbcb-11e6-97bb-1738584f85d7.png)
