### ISSUE TITLE
Resizing to full screen doesn't scale the fonts appropriately

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#23]

**Comment by ililush** [comment]
if i scale down the window, and the iframe is limited to 700*500 than i sometimes cannot see the whole text, and i get three dots ...
is this what you mean regarding scaling the fonts?
![text_on_cards](https://cloud.githubusercontent.com/assets/18185033/21883761/4409e76e-d8b9-11e6-9366-5291e307c32c.png)

**Comment by sebastientromp** [comment]
Are you talking about the dots on the carousel or on the game player?

The font scaling for now only occurs on the player

**Comment by ililush** [comment]
full screen, and still the description text beneith the image is with ...
@sebastientromp what happens at zero2heroes site when you have a long line?
![text_is_](https://cloud.githubusercontent.com/assets/18185033/21961020/3407941a-db07-11e6-8e47-7950025755f1.png)

**Comment by sebastientromp** [comment]
The starting "..." from "... which deals 1 damage to" are part of the text and are used to show that the effect is a consequence of the previous action. Or are you referring to something else?
And on ZetoH I need to check - the desired behavior is that the text be displayed on several lines
