### ISSUE TITLE
victory crown is cut in the match carousel

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#26]
![1](https://cloud.githubusercontent.com/assets/18185033/21881511/5dd50dd8-d8ad-11e6-97da-97b0b6de5f2d.png)

**Comment by sebastientromp** [comment]
overflow on the list is hidden, which causes the crown to be cut.
However, setting the overflow to "visible" make the games that should be out of the screen to appear, so it's not a solution

**Comment by ililush** [comment]
this is fixed - can be closed.
