### ISSUE TITLE
favicon icon in game summary header is PNG and hence has wrong colors

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#27]
hi :)
i think that the transparent parts of the favicon are causing the image to not be accurate as far as colors. see attached images of the icon and the way it looks in GS (game summary).
![z2hfavicon](https://cloud.githubusercontent.com/assets/18185033/21881689/fd37bfb8-d8af-11e6-8cfe-94172a87b8d0.png)
![2017-01-12_1015](https://cloud.githubusercontent.com/assets/18185033/21881709/0f154034-d8b0-11e6-822a-51858b5b9976.png)

**Comment by sebastientromp** [comment]
Hey ilil, the issue is invisible to my untrained eyes :)
Any idea how we might fix this?

**Comment by ililush** [comment]
:) yes, i will ask Gai to fix this :)

**Comment by chukumuki** [comment]
here is an updated icon with white belly
[zero-to-heroes-logo.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/706469/zero-to-heroes-logo.zip)
