### ISSUE TITLE
after playing HS, i did not get the data for the last game i played (that had 2 matches in it), but the same game i played before that.

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#28]

**Comment by ililush** [comment]
happened again this morning so this isn't fixed.

**Comment by sebastientromp** [comment]
I'm having another issue - first session is going well (2 games played, and 2 games displayed on the EGS), but when I start the game once again I get a "Not accepting shelves" error. Not happening every time though

**Comment by ililush** [comment]
where is this issue located? you end? our end?

**Comment by sebastientromp** [comment]
I don't know :) The "Not accepting shelves" is returned by OW, but I have no idea what causes it to return it sometimes and not others

**Comment by sebastientromp** [comment]
Found the root cause of the initial issue - I was looking at the "gameChanged" attribute of the GameInfoResult to see if I needed to start the log parsing

**Comment by ililush** [comment]
finally fixed for me! :)
