### ISSUE TITLE
opponent hit points are hidden by minions on the table

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#29]
see attached images:
![700_500](https://cloud.githubusercontent.com/assets/18185033/21884327/819b0c8c-d8bb-11e6-933e-1434e59c52a6.png)
![2017-01-12_1137](https://cloud.githubusercontent.com/assets/18185033/21884361/a33ffc1c-d8bb-11e6-8503-1d038af6d7d8.png)

**Comment by ililush** [comment]
this is fixed - can be closed.

**Comment by sebastientromp** [comment]
Nice - was doing the fix mostly blind since I couldn't interact with the game :)
