### ISSUE TITLE
card description text is almost unreadable - was there a quality downgrade?

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#30]
![2017-01-12_1139_001](https://cloud.githubusercontent.com/assets/18185033/21884416/e145daa4-d8bb-11e6-9224-ddef129d1697.png)
![2017-01-12_1139](https://cloud.githubusercontent.com/assets/18185033/21884419/e3753892-d8bb-11e6-9aad-2da958e755e8.png)

**Comment by sebastientromp** [comment]
It might be because of the compressed images that we tried to use to save bandwith. I'll fallback to the uncompressed images and see how it goes

**Comment by ililush** [comment]
from my end this is fixed - text is now readable
![text_visibility_fixed](https://cloud.githubusercontent.com/assets/18185033/21960881/bb8c933c-db01-11e6-87ee-cfeeeecf304b.png)

**Comment by sebastientromp** [comment]
Perfect - this means I probably have some tuning to do with image compression, but will keep that for later
