### ISSUE TITLE
game thumbnail - remove unnecessary inner background and border

### ISSUE THREAD

**Issue by chukumuki** [Zero-to-Heroes/overwolf-replay-app#31]
in game-thumbnail.component.scss, line 61, please delete:

.game.selected {
    border: #68471f 1px solid;
    background-color: rgba(104, 71, 31, 0.2);
}

![image](https://cloud.githubusercontent.com/assets/24590906/21890428/5e27aed4-d8d6-11e6-9e54-f207037a30cd.png)

**Comment by ililush** [comment]
this can be closed.
