### ISSUE TITLE
If game already present in the logs from a previous session, don't show it in carousel

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#32]
Not sure exactly if this can be done or how (Blizzard doesn't provide real timestamps), but keeping track of it at least

**Comment by ililush** [comment]
hi, how do i test it?

**Comment by sebastientromp** [comment]
Launch HS, play a game, exit HS, relaunch, check the Hearthstone/Logs/Power.log file is still present, play a game -> you should have only the latest one.
