### ISSUE TITLE
clicking on the play bar minimizes the screen

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#33]
This happens also if i press many other spots in this area:
![image](https://cloud.githubusercontent.com/assets/18185033/21960867/139f786a-db01-11e6-90bc-211be98ec6ad.png)

to reproduce:
1. open EGS
2. maximize screen
3. left click on the progress bar

**Comment by sebastientromp** [comment]
Will look at it once I can once again interact with the EGS

**Comment by sebastientromp** [comment]
This is caused by the "resize" and "move" handlers that were left on the shelf for dev purposes, removing them fixes the issue
