### ISSUE TITLE
following issue 36 - after clicking a button the mouse over stays (blue situation)

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#37]
after clicking the button indicator is not the blue color (it's the mouse over indication).
![image](https://cloud.githubusercontent.com/assets/18185033/21961411/c07b01b6-db11-11e6-8c40-67211369e3ff.png)

**Comment by sebastientromp** [comment]
I'm not sure what the current / expected behavior is. Would you mind detailing it a bit more for me?

**Comment by ililush** [comment]
yes,

see attached screenshot - play button should be blue on mouse over. "state" buttons are toggle and should be blue when "on"

![mouse_over_-_on_off_toggle](https://cloud.githubusercontent.com/assets/18185033/21961500/c8c2fac0-db13-11e6-9e30-fa04cb68d1e7.png)

**Comment by sebastientromp** [comment]
Much clearer, go it :)
Today the play buttons staying blue is unintended, I'll look into that, and will add the behaviour for the other mode buttons
