### ISSUE TITLE
when you start a turn it says 10 and than it's 1, afterwards it's turn 20 and than it's 2

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#39]
it doesn't count 1,2,3,4, but 10,1,20,2,30,3 40,4 etc.

**Comment by sebastientromp** [comment]
It's actually "2o" (for opponent). The current font makes it not that easy to distinguish from "20" though.
I'm open to suggestions, the constraints I have are:
* It needs to be short
* It can be typed easily on a keyboard (in the comments, when you type "turn 2o" or "t2o" you get a direct hyperlink to display the replay at turn 2o

**Comment by ililush** [comment]
maybe add /
2/o
3/o
?

**Comment by sebastientromp** [comment]
The / will interfere in the URL (you can add ts=t2 or ts=t2o in the URL to go directly to a specific turn), so I think a non-escaped character will work better

**Comment by ililush** [comment]
hmmm maybe instead of o for opponent we can use R for Rival? :) that way it will not be confused with a number?

**Comment by ililush** [comment]
another option is creating a tooltip that shows the entire turn title (like the log in your website): "Turn 1 - username"

**Comment by sebastientromp** [comment]
You mean when mousing over the turrn button?

**Comment by ililush** [comment]
yes
