### ISSUE TITLE
after window re-size tooltips over play buttons stop working

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#41]

**Comment by sebastientromp** [comment]
I couldn't reproduce this one. Do you have any specific scenario that causes the issue?

**Comment by ililush** [comment]
hi, yes:
1. open game summary
2. manually drag the edges to slightly enhance the screen

**Comment by sebastientromp** [comment]
Did that, but still can't reproduce:

![image](https://cloud.githubusercontent.com/assets/7889624/22009584/79272758-dc84-11e6-9ce0-96f33c812423.png)
(after resizing the EGS)

**Comment by ililush** [comment]
maybe we can do a screen share?

**Comment by sebastientromp** [comment]
I'm not available during the day for this. An animated gif? :)

**Comment by ililush** [comment]
hope this helps:

**Comment by ililush** [comment]
[tooltip_not_showing_after_manual_screen_size_change.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/710612/tooltip_not_showing_after_manual_screen_size_change.zip)

**Comment by sebastientromp** [comment]
Just clicking back on the shelf restores the tooltip. That's pretty standard HTML behavior I think, so I'm not sure it's worth trying to work around this, is it?

**Comment by ililush** [comment]
The expectation is to have the tooltip available without clicking the shelf. is that possible?

**Comment by sebastientromp** [comment]
I honestly don't know - if you click on anything outside of the shelf you still can interact with it, but when resizing it looks like you completely lose the interaction.
I need to test that tonight, but I don't think the mouse cursor changes to a pointer when going over the controls, nor are the card tooltips shown. If they are we can probably do something, but if they aren't then it's probably a broader issue than just the tooltip.

**Comment by ililush** [comment]
we are checking this internally, it is the iframe behavior to lose focus at resize. Maybe we can fix this on our end - let us check before you spend a night over it, ok? :)
