### ISSUE TITLE
tooltips pointer should be alligned to button center

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#42]
![tooltips_not_alligned](https://cloud.githubusercontent.com/assets/18185033/21975041/0dc61a34-dbd3-11e6-9cfe-c0fda611334a.png)

**Comment by ililush** [comment]
stil not centered. maybe gai can asisst? 
![still_not_centered_tooltip](https://cloud.githubusercontent.com/assets/18185033/22011321/1a725b0c-dc97-11e6-94df-54c99d142269.png)

**Comment by sebastientromp** [comment]
Do you use a tool to know the centered / not centered? I did a quick check with Paint.NET and found that the arrow was precisely at the center of the icon. But my measure may not have been 100% precise
