### ISSUE TITLE
no space between user name and "vs"

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#43]
see screenshot. 

![screenshot_16](https://cloud.githubusercontent.com/assets/18185033/21982642/024cbb68-dbf6-11e6-91a2-8387e0432184.png)

**Comment by sebastientromp** [comment]
I assume this is because the username is too big. The alternative is to limit the possible length of the name and use ellipsis instead, like what happens for the opponent

**Comment by sebastientromp** [comment]
I have added the ellipsis overflow, let me know what you think. Maybe simply truncating / clipping the name would be better

**Comment by ililush** [comment]
much better.
