### ISSUE TITLE
v0.13 installed - no data in iframe after session

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#46]
attached screenshot + console
i'm not touching anything, so let me know if you need additional data from my computer.
![console_for_no_iframe](https://cloud.githubusercontent.com/assets/18185033/22182207/3855a11e-e0a8-11e6-8e43-806e2fb14929.png)
![no_iframe_data](https://cloud.githubusercontent.com/assets/18185033/22182208/3855ce14-e0a8-11e6-9f66-f7f10f840642.png)

**Comment by sebastientromp** [comment]
Fixed with hotfix is 0.13.1
