### ISSUE TITLE
When game summary screen opens not i full screen and carousel does not show all tiles - a tile shows for a split second before full screen load

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#48]
i don't think i can explain this well on text so i made a small video - tell me if you can watch it. (unzip and drag to chrome)
[4th_tile_apears_for_a_second_and_than_disappears.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/731731/4th_tile_apears_for_a_second_and_than_disappears.zip)

**Comment by sebastientromp** [comment]
Got it, it's because of the way I decide which games should / should not be visible in the carousel. I'll see if I can remove the glitch
