### ISSUE TITLE
An oversized card is displayed when hovering the name of the button within the action description

### ISSUE THREAD

**Issue by yanco77** [Zero-to-Heroes/overwolf-replay-app#51]
See attached image.

![zth - oversized card](https://cloud.githubusercontent.com/assets/25452052/22461213/0c16a1b0-e7b1-11e6-9bbf-bab969fd5b38.png)

**Comment by sebastientromp** [comment]
Got it, I hadn't understood the issues were when mousing over the text. Issue identified, a fix will be available in the next version

**Comment by ililush** [comment]
does not reproduce for me.
