### ISSUE TITLE
The display of the card stutters when moving the cursor across the name of the card within the action description

### ISSUE THREAD

**Issue by yanco77** [Zero-to-Heroes/overwolf-replay-app#52]
See animated GIF.
![zth - card stuttering](https://cloud.githubusercontent.com/assets/25452052/22461328/7a091b62-e7b1-11e6-836e-a31e001e2a56.gif)

**Comment by sebastientromp** [comment]
Got it, I hadn't understood the issues were when mousing over the text. Issue identified, a fix will be available in the next version

**Comment by ililush** [comment]
Does not reproduce for me.
