### ISSUE TITLE
 if i reach the end of the session replay and i try to go back to earlier steps GS freezes and then crashes.

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#54]

**Comment by sebastientromp** [comment]
Could you attack the Hearthstone logs?

**Comment by sebastientromp** [comment]
Reproduced - can you confirm this doesn't happen when clicking on the arrows, but only when clicking on the timeline?

**Comment by ililush** [comment]
this happens in various situations. for me it happens if i click arrows, time line, or it just spontaneously crashes. Tom will review this from our side shortly.

**Comment by sebastientromp** [comment]
What I reproduced was that when on the end screen, I could not click on the timeline to move. No crash however, and using the arrows let me move around the game without any issue

**Comment by ililush** [comment]
it does not reproduce with v21, so it was probably the logs as Elad suggested (one of our engineers).
