### ISSUE TITLE
changing game speed enables "play"

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#55]
in the following flow:

1. GS opens
2. change game speed from 0 to anything else
3. game starts playing

expected - player should not start playing until "play" is pressed.

**Comment by sebastientromp** [comment]
How much do you need this change? Today, play / pause is actually nothing more than a speed > 0 or == 0, so changing this requires changing the way play and pause work, and no one using the site has reported that this behavior was strange to them.

**Comment by sebastientromp** [comment]
Is this really a show stopper? The current behavior is how I would want it to work (and the reason I designed it that way). If this is serious enough to block the release I'll change it, but I'd like to be sure it's worth the effort.

**Comment by ililush** [comment]
This does need to be solved as this is a clunky experience. the only action that should enable play is pushing the play button, but i'm removing the show stopper.

**Comment by sebastientromp** [comment]
Fixed with 7133a38
