### ISSUE TITLE
 play start but is not indicated in the player timeline

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#56]
![ff_turn_3_timeline_wrong_ink_li](https://cloud.githubusercontent.com/assets/18185033/22625004/5d173bc0-eb93-11e6-88e0-6e4222d1884d.jpg)

**Comment by sebastientromp** [comment]
Could you please attach the Hearthstone logs?

**Comment by sebastientromp** [comment]
Today there is no fallback to the most recent timestamp if the current action doesn't have an associated timestamp. Fix ongoing
