### ISSUE TITLE
Hovering on card name in text description causes images to freeze and than stack

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#59]
to reproduce:
1. start playing a match
2. mouse over the text describing the action, over the card name
3. a card will appear, after a number of mouse over it will get "stuck"
4. repeating the action will create a number of card stacking on top of each other
![mouse_over_text](https://cloud.githubusercontent.com/assets/18185033/22637618/8b8ffd26-ec4b-11e6-87d6-6e3d271efa96.png)
![2017-02-06_0844](https://cloud.githubusercontent.com/assets/18185033/22637619/8b904ccc-ec4b-11e6-83a1-a121ac6e5e81.png)

**Comment by sebastientromp** [comment]
I'll have a look, but it might be something to fix in the third party I'm using to handle tooltips. Will keep you posted

**Comment by sebastientromp** [comment]
Found a hack I can use to solve the issue. Testing it and I'll build a new release once it's done

**Comment by ililush** [comment]
fixed! :)
