### ISSUE TITLE
carousel navigation is clunky

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#60]
see attached video.
expected behavior:
1. scrolling down can only scroll until the last item in the carousel - remove empty spaces.
2. navigation up should be unanimous - either one tile at a time or full page at a time.

[Zero to Hero carousel bug.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/754526/Zero.to.Hero.carousel.bug.zip)

**Comment by sebastientromp** [comment]
> scrolling down can only scroll until the last item in the carousel - remove empty spaces.

I can change this, though I find that it's clearer if you always scroll 3 by 3 (or by whatever amount you display) since we have pagination instead of scrolling.

> navigation up should be unanimous - either one tile at a time or full page at a time.

That's a bug indeed, it should behave symmetrically to the navigation down

**Comment by sebastientromp** [comment]
Fixes 1) and 2)

**Comment by ililush** [comment]
fixed indeed 👍
