### ISSUE TITLE
Differentiate Spectate mode

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#62]
Looking at Power.log, apparently there is a specific line that tells you who you're spectating, so that should make it a bit easier :)

[Power.log.txt](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/830457/Power.log.txt)

**Comment by ililush** [comment]
this is great news :)

**Comment by sebastientromp** [comment]
Did a short prototype, we could do something like this (text / color can be changed easily):

![image](https://cloud.githubusercontent.com/assets/7889624/23746555/aadec9d0-04bc-11e7-95e5-ffec6cf61393.png)
