### ISSUE TITLE
Shelf is not displayed at the right size in EGS

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/overwolf-replay-app#9]
Might be because the manifest specifies an 800x600 size and not resizable?

**Comment by sebastientromp** [comment]
Removing all size indications from the manifest didn't solve the issue, will need help on this

**Comment by sebastientromp** [comment]
Height is fixed based on contents of manifest.json, but doesn't scale up when resizing the EGS.

**Comment by ililush** [comment]
for me this is fixed and can be closed.
